### ISSUE TITLE
Split `Connection String` field in credentials into different fields 

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/postgresql-component#13]
**Description:**

Currently one have to enter an MSSQL URI as a string like:

```mssql://username:password@localhost/database```

Issues with it:

 - Not user friendly
 - Password is visible in UI and not protected

**AR:**
Currently field for credentials input looks like:
![image](https://user-images.githubusercontent.com/36419533/57311924-3fba8e80-70f5-11e9-939f-1ebebdfdad10.png)

**ER:** split into fields as in Database component:
![image](https://user-images.githubusercontent.com/36419533/57312052-785a6800-70f5-11e9-97db-578493767f03.png)

**Comment by kirill-levitskiy** [comment]
There is a feature request from the customer:

We are able to connect directly to Redshift form the Elastic; however, we do have one concern. The connection string that we use for Redshift (using Postgress driver) includes the username and password. For instance, our connection string is: postgress://username:pa$word@your.postgresql.host:5432/dbname
 
However, for security reasons it would probably be good to separate these credentials from the connection string.
