### ISSUE TITLE
Retry in case of deadlocked transaction

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/postgresql-component#18]
When trying to run a query to INSERT/UPDATE data in a database user may get an error about unexpected termination due to locked resource, like this:
`Transaction was deadlocked on lock resources with another process. Rerun the transaction.`

There will be great to have additional option (checkbox) to perform retries based on rebound mechanism to avoid termination of flow's processing or in-build mechanism of retries with two optional fields in the Configuration of a Step: `Number of retries` amd `Delay between retries` and as default `Number of retries = 0`.

For example, if we are building fix based on rebound mechanism:
To add checkbox Retry on error, if possible to step's configuration. The logic should perform limited number of request's retries (for example 3) in case of errors that can be theoretically solved by retry within a short time.

**Comment by A3a3e1** [comment]
Pay attention to detailed documentation
