### ISSUE TITLE
Component can not be used with Heroku hosted instances

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/postgresql-component#33]
## Useful Info:
* https://help.heroku.com/MDM23G46/why-am-i-getting-an-error-when-i-upgrade-to-pg-8
* https://devcenter.heroku.com/articles/getting-started-with-nodejs?singlepage=true
* https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres

## Problem
Currently, the component can't connect to postgres SQL databases hosted on heroku. It seems as though the root cause of this is problem may be that heroku is using self-signed SSL certificates and that some options within how the connection is established must be changed. The component should be modified in such a way so that this becomes possible.  (Either by adding a **Allow self-signed certificates** checkbox to the credential or by adding an input to the credentials to specify additional query-string options.)

**Comment by shulkaolka** [comment]
Estimation include sailor update and annual npm vulnerabilities audit
