### ISSUE TITLE
Code review and tests request

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/postgresql-component#5]
Required a code review and tests of updates in the component.

PR: https://github.com/elasticio/postgresql-component/pull/4

SP: 13

**Comment by stas-fomenko** [comment]
**CDoD**

**Development:**
- [ ] Code is written and formatted in accordance with the Styling guide.
- [ ] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests.
- [ ] Triggers/actions comply with OIH patterns.
- [ ] Documentation (README.md file in the Github) is 100% ready. 
- [ ] Component code is covered with integration tests.
- [ ] Component code is reviewed and fixed, if needed.
- [ ] CI is set up
- [ ] Sprint review preparation is finished (build demo flow is built)

**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] All the development branches are reviewed and merged into master
- [ ] Component is deployed to the production stage (app.elastic.io)
  - Smoke test is finished there.
  - Component has a proper access level
- [ ] Release notes are done. 
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated.

**Comment by stas-fomenko** [comment]
reviewed, tested, pushed to production
